### ISSUE TITLE
merge to phpcs upstream?

### ISSUE THREAD

**Issue by imme-emosol** [Linnk/Allman_CodeSniffer#1]
Will you be working towards integrating your code to the codebase of phpcs ?

It seems there is some demand for it; https://github.com/squizlabs/PHP_CodeSniffer/issues/2025 .

**Comment by Linnk** [comment]
Oh wow! I never thought someone else would want to use it. It's been a while since I've worked on this, but maybe I can make time and try a pull request in few days. I would love integrating this.

**Comment by Herz3h** [comment]
Yes please do !

**Comment by garretthyder** [comment]
Would love to see this get integrated, thanks.
